INFO 2025-05-26 21:35:53,523 autoreload 72659 133110179778816 Watching for file changes with StatReloader
INFO 2025-05-26 21:38:41,386 autoreload 73484 130514372940032 Watching for file changes with StatReloader
INFO 2025-05-26 21:40:21,030 autoreload 73606 137794581025024 Watching for file changes with StatReloader
INFO 2025-05-26 21:41:20,502 autoreload 73746 129963440222464 Watching for file changes with StatReloader
INFO 2025-05-26 21:42:47,038 autoreload 73606 137794581025024 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:42:47,235 autoreload 73746 129963440222464 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:42:47,805 autoreload 73816 135725891322112 Watching for file changes with StatReloader
INFO 2025-05-26 21:42:48,192 autoreload 73817 129445097074944 Watching for file changes with StatReloader
INFO 2025-05-26 21:43:40,972 autoreload 73816 135725891322112 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:43:41,412 autoreload 73817 129445097074944 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:43:41,760 autoreload 73925 128234618155264 Watching for file changes with StatReloader
INFO 2025-05-26 21:43:42,282 autoreload 73926 126588364108032 Watching for file changes with StatReloader
INFO 2025-05-26 21:43:51,317 autoreload 73925 128234618155264 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:43:51,837 autoreload 73926 126588364108032 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:43:51,859 autoreload 74003 131136034423040 Watching for file changes with StatReloader
INFO 2025-05-26 21:43:52,466 autoreload 74006 135781382271232 Watching for file changes with StatReloader
INFO 2025-05-26 21:44:44,127 autoreload 74006 135781382271232 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:44:44,562 autoreload 74003 131136034423040 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:44:51,489 autoreload 74096 136683908907264 Watching for file changes with StatReloader
INFO 2025-05-26 21:44:53,666 autoreload 74097 124760162074880 Watching for file changes with StatReloader
INFO 2025-05-26 21:44:57,979 autoreload 74097 124760162074880 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:44:58,316 autoreload 74096 136683908907264 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:44:59,861 autoreload 74209 127478609850624 Watching for file changes with StatReloader
INFO 2025-05-26 21:45:00,784 autoreload 74218 130482527691008 Watching for file changes with StatReloader
INFO 2025-05-26 21:48:19,153 autoreload 74218 130482527691008 /home/medical_system/backend/airesults/views.py changed, reloading.
INFO 2025-05-26 21:48:19,844 autoreload 74209 127478609850624 /home/medical_system/backend/airesults/views.py changed, reloading.
INFO 2025-05-26 21:48:20,587 autoreload 74528 123994980589824 Watching for file changes with StatReloader
INFO 2025-05-26 21:48:20,708 autoreload 74529 133233674264832 Watching for file changes with StatReloader
INFO 2025-05-26 21:49:57,521 autoreload 74529 133233674264832 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:49:57,585 autoreload 74528 123994980589824 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:49:58,413 autoreload 74647 127974149206272 Watching for file changes with StatReloader
INFO 2025-05-26 21:49:58,520 autoreload 74648 134642769600768 Watching for file changes with StatReloader
INFO 2025-05-26 21:51:39,106 autoreload 74647 127974149206272 /home/medical_system/backend/airesults/views.py changed, reloading.
INFO 2025-05-26 21:51:39,435 autoreload 74648 134642769600768 /home/medical_system/backend/airesults/views.py changed, reloading.
INFO 2025-05-26 21:51:39,917 autoreload 74760 130642693533952 Watching for file changes with StatReloader
INFO 2025-05-26 21:51:40,363 autoreload 74761 131052325974272 Watching for file changes with StatReloader
INFO 2025-05-26 21:54:07,817 autoreload 74761 131052325974272 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:54:08,430 autoreload 74760 130642693533952 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:54:08,438 autoreload 74898 131295205118208 Watching for file changes with StatReloader
INFO 2025-05-26 21:54:09,203 autoreload 74900 138217886503168 Watching for file changes with StatReloader
INFO 2025-05-26 21:55:24,043 autoreload 74898 131295205118208 /home/medical_system/backend/airesults/views.py changed, reloading.
INFO 2025-05-26 21:55:24,468 autoreload 74900 138217886503168 /home/medical_system/backend/airesults/views.py changed, reloading.
INFO 2025-05-26 21:55:24,686 autoreload 75025 140248063766784 Watching for file changes with StatReloader
INFO 2025-05-26 21:55:25,414 autoreload 75027 127178527166720 Watching for file changes with StatReloader
INFO 2025-05-26 21:56:22,427 autoreload 75027 127178527166720 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:56:23,120 autoreload 75025 140248063766784 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:56:23,870 autoreload 75181 130257462550784 Watching for file changes with StatReloader
INFO 2025-05-26 21:56:24,932 autoreload 75206 132915197911296 Watching for file changes with StatReloader
INFO 2025-05-26 21:56:37,243 autoreload 75206 132915197911296 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:56:37,422 autoreload 75181 130257462550784 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:56:38,672 autoreload 75298 127988970782976 Watching for file changes with StatReloader
INFO 2025-05-26 21:56:38,972 autoreload 75303 128369638392064 Watching for file changes with StatReloader
INFO 2025-05-26 21:56:41,200 autoreload 75298 127988970782976 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:56:41,373 autoreload 75303 128369638392064 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:56:41,970 autoreload 75336 128788673376512 Watching for file changes with StatReloader
INFO 2025-05-26 21:56:42,233 autoreload 75337 126702443483392 Watching for file changes with StatReloader
INFO 2025-05-26 21:56:58,656 autoreload 75336 128788673376512 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:56:58,762 autoreload 75337 126702443483392 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:57:00,511 autoreload 75440 124260938563840 Watching for file changes with StatReloader
INFO 2025-05-26 21:57:00,637 autoreload 75441 127180784783616 Watching for file changes with StatReloader
INFO 2025-05-26 21:58:12,842 autoreload 75441 127180784783616 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:58:12,872 autoreload 75440 124260938563840 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 21:58:14,703 autoreload 75583 136591462723840 Watching for file changes with StatReloader
INFO 2025-05-26 21:58:14,703 autoreload 75582 136863802396928 Watching for file changes with StatReloader
INFO 2025-05-26 21:59:21,741 autoreload 75829 126368528482560 Watching for file changes with StatReloader
ERROR 2025-05-26 21:59:31,024 exception 75582 136859898996416 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 21:59:31,064 log 75582 136859898996416 Bad Request: /
WARNING 2025-05-26 21:59:31,065 basehttp 75582 136859898996416 "GET / HTTP/1.1" 400 76651
ERROR 2025-05-26 21:59:31,661 exception 75582 136859890603712 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 21:59:31,687 log 75582 136859890603712 Bad Request: /favicon.ico
WARNING 2025-05-26 21:59:31,687 basehttp 75582 136859890603712 "GET /favicon.ico HTTP/1.1" 400 76707
ERROR 2025-05-26 21:59:48,292 exception 75582 136859898996416 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 21:59:48,321 log 75582 136859898996416 Bad Request: /favicon.ico
WARNING 2025-05-26 21:59:48,321 basehttp 75582 136859898996416 "GET /favicon.ico HTTP/1.1" 400 76707
INFO 2025-05-26 21:59:51,616 basehttp 75582 136859890603712 code 400, message Bad request version ('çö4#"\x91¯àe\x9eÂ4°É7\x97ÊRPç')
ERROR 2025-05-26 21:59:51,616 basehttp 75582 136859890603712 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-05-26 21:59:51,620 basehttp 75582 136859890603712 code 400, message Bad request version ('«')
ERROR 2025-05-26 21:59:51,620 basehttp 75582 136859890603712 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-05-26 21:59:51,976 basehttp 75582 136859890603712 code 400, message Bad request version ('ÿ©}«j¯')
ERROR 2025-05-26 21:59:51,977 basehttp 75582 136859890603712 You're accessing the development server over HTTPS, but it only supports HTTP.
INFO 2025-05-26 21:59:51,981 basehttp 75582 136859890603712 code 400, message Bad request version ('©\x05@£#²S&~?sÇ\x03ÚTÜë9°\x87.\x19êmÜø×\x8c\x1aêï8w¬l¸QN\x9f#r\x88Ê\x86\x08ÎÔÊg@©x\x08$\x8a\x12\x13Yâ\x9e\x87&rùÊzñ»H\x83')
ERROR 2025-05-26 21:59:51,981 basehttp 75582 136859890603712 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2025-05-26 21:59:54,004 exception 75582 136859881162432 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 21:59:54,028 log 75582 136859881162432 Bad Request: /favicon.ico
WARNING 2025-05-26 21:59:54,029 basehttp 75582 136859881162432 "GET /favicon.ico HTTP/1.1" 400 76707
INFO 2025-05-26 22:00:25,579 autoreload 75582 136863802396928 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:00:26,818 autoreload 75996 138784815337728 Watching for file changes with StatReloader
INFO 2025-05-26 22:00:34,832 autoreload 75996 138784815337728 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:00:36,312 autoreload 76035 128173817716992 Watching for file changes with StatReloader
ERROR 2025-05-26 22:02:03,792 exception 76035 128169907181248 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 22:02:03,823 log 76035 128169907181248 Bad Request: /
WARNING 2025-05-26 22:02:03,824 basehttp 76035 128169907181248 "GET / HTTP/1.1" 400 76788
ERROR 2025-05-26 22:02:04,389 exception 76035 128169915573952 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 22:02:04,417 log 76035 128169915573952 Bad Request: /favicon.ico
WARNING 2025-05-26 22:02:04,417 basehttp 76035 128169915573952 "GET /favicon.ico HTTP/1.1" 400 76707
ERROR 2025-05-26 22:02:25,929 exception 76035 128169907181248 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 22:02:25,960 log 76035 128169907181248 Bad Request: /
WARNING 2025-05-26 22:02:25,961 basehttp 76035 128169907181248 "GET / HTTP/1.1" 400 76788
ERROR 2025-05-26 22:02:26,523 exception 76035 128169915573952 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 22:02:26,546 log 76035 128169915573952 Bad Request: /favicon.ico
WARNING 2025-05-26 22:02:26,547 basehttp 76035 128169915573952 "GET /favicon.ico HTTP/1.1" 400 76707
ERROR 2025-05-26 22:02:59,607 exception 76035 128169907181248 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 22:02:59,630 log 76035 128169907181248 Bad Request: /
WARNING 2025-05-26 22:02:59,631 basehttp 76035 128169907181248 "GET / HTTP/1.1" 400 76788
ERROR 2025-05-26 22:03:00,192 exception 76035 128169897739968 Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/backend/venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '35.225.63.41:8000'. You may need to add '35.225.63.41' to ALLOWED_HOSTS.
WARNING 2025-05-26 22:03:00,215 log 76035 128169897739968 Bad Request: /favicon.ico
WARNING 2025-05-26 22:03:00,215 basehttp 76035 128169897739968 "GET /favicon.ico HTTP/1.1" 400 76707
INFO 2025-05-26 22:04:05,952 autoreload 76035 128173817716992 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:04:50,067 autoreload 76352 129255361589504 Watching for file changes with StatReloader
WARNING 2025-05-26 22:04:56,925 log 76352 129251430491840 Not Found: /
WARNING 2025-05-26 22:04:56,926 basehttp 76352 129251430491840 "GET / HTTP/1.1" 404 2837
WARNING 2025-05-26 22:04:57,302 log 76352 129251430491840 Not Found: /favicon.ico
WARNING 2025-05-26 22:04:57,303 basehttp 76352 129251430491840 "GET /favicon.ico HTTP/1.1" 404 2888
ERROR 2025-05-26 22:10:05,567 log 76352 129251422099136 Internal Server Error: /api/study-requests/
Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 72, in page
    number = self.validate_number(number)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 53, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 99, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 536, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 522, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")
ERROR 2025-05-26 22:10:05,577 basehttp 76352 129251422099136 "GET /api/study-requests/ HTTP/1.1" 500 221308
ERROR 2025-05-26 22:10:05,815 log 76352 129251430491840 Internal Server Error: /api/study-requests/
Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 72, in page
    number = self.validate_number(number)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 53, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 99, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 536, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 522, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")
ERROR 2025-05-26 22:10:05,821 basehttp 76352 129251430491840 "GET /api/study-requests/ HTTP/1.1" 500 221308
ERROR 2025-05-26 22:10:07,526 log 76352 129251336517312 Internal Server Error: /api/study-requests/
Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 72, in page
    number = self.validate_number(number)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 53, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 99, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 536, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 522, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")
ERROR 2025-05-26 22:10:07,535 basehttp 76352 129251336517312 "GET /api/study-requests/ HTTP/1.1" 500 221308
ERROR 2025-05-26 22:10:15,241 log 76352 129251319731904 Internal Server Error: /api/study-requests/
Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
                ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 72, in page
    number = self.validate_number(number)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 53, in validate_number
    if number > self.num_pages:
                ^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 99, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
       ^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 536, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/query.py", line 522, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "/home/medical_system/venv/lib/python3.13/site-packages/MySQLdb/connections.py", line 255, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: (1146, "Table 'medical_platform.worklist_studyrequest' doesn't exist")
ERROR 2025-05-26 22:10:15,247 basehttp 76352 129251319731904 "GET /api/study-requests/ HTTP/1.1" 500 221308
INFO 2025-05-26 22:13:53,170 views 76352 129251302946496 OpenMRS 연결 성공
INFO 2025-05-26 22:13:53,225 orthanc_api 76352 129251302946496 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:13:53,231 views 76352 129251302946496 Orthanc 연결 성공
INFO 2025-05-26 22:13:53,238 basehttp 76352 129251302946496 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:13:53,506 views 76352 129251302946496 OpenMRS 연결 성공
INFO 2025-05-26 22:13:53,532 orthanc_api 76352 129251302946496 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:13:53,537 views 76352 129251302946496 Orthanc 연결 성공
INFO 2025-05-26 22:13:53,546 basehttp 76352 129251302946496 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:13:54,119 views 76352 129251302946496 OpenMRS 연결 성공
INFO 2025-05-26 22:13:54,125 orthanc_api 76352 129251302946496 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:13:54,126 views 76352 129251302946496 Orthanc 연결 성공
INFO 2025-05-26 22:13:54,128 basehttp 76352 129251302946496 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:13:55,243 views 76352 129251302946496 OpenMRS 연결 성공
INFO 2025-05-26 22:13:55,251 orthanc_api 76352 129251302946496 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:13:55,252 views 76352 129251302946496 Orthanc 연결 성공
INFO 2025-05-26 22:13:55,253 basehttp 76352 129251302946496 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:14:00,080 views 76352 129251302946496 OpenMRS 연결 성공
INFO 2025-05-26 22:14:00,087 orthanc_api 76352 129251302946496 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:14:00,088 views 76352 129251302946496 Orthanc 연결 성공
INFO 2025-05-26 22:14:00,090 basehttp 76352 129251302946496 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:16:53,219 views 76352 129251286161088 OpenMRS 연결 성공
INFO 2025-05-26 22:16:53,232 orthanc_api 76352 129251286161088 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:16:53,234 views 76352 129251286161088 Orthanc 연결 성공
INFO 2025-05-26 22:16:53,237 basehttp 76352 129251286161088 "GET /api/test-connections/ HTTP/1.1" 200 66
ERROR 2025-05-26 22:16:55,411 openmrs_api 76352 129251286161088 환자 검색 실패 (검색어: 'ㅇ'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=%E3%85%87&v=full
ERROR 2025-05-26 22:16:55,414 log 76352 129251286161088 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:16:55,416 basehttp 76352 129251286161088 "GET /api/openmrs/patients/search/?q=%E3%85%87 HTTP/1.1" 500 47
ERROR 2025-05-26 22:16:56,664 openmrs_api 76352 129251286161088 환자 검색 실패 (검색어: 'j'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=j&v=full
ERROR 2025-05-26 22:16:56,668 log 76352 129251286161088 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:16:56,670 basehttp 76352 129251286161088 "GET /api/openmrs/patients/search/?q=j HTTP/1.1" 500 47
ERROR 2025-05-26 22:16:56,855 openmrs_api 76352 129250732537536 환자 검색 실패 (검색어: 'jo'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=jo&v=full
ERROR 2025-05-26 22:16:56,858 log 76352 129250732537536 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:16:56,859 basehttp 76352 129250732537536 "GET /api/openmrs/patients/search/?q=jo HTTP/1.1" 500 47
ERROR 2025-05-26 22:16:58,095 openmrs_api 76352 129250732537536 환자 검색 실패 (검색어: 'jon'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=jon&v=full
ERROR 2025-05-26 22:16:58,096 log 76352 129250732537536 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:16:58,096 basehttp 76352 129250732537536 "GET /api/openmrs/patients/search/?q=jon HTTP/1.1" 500 47
ERROR 2025-05-26 22:16:58,443 openmrs_api 76352 129250732537536 환자 검색 실패 (검색어: 'jo'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=jo&v=full
ERROR 2025-05-26 22:16:58,445 log 76352 129250732537536 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:16:58,446 basehttp 76352 129250732537536 "GET /api/openmrs/patients/search/?q=jo HTTP/1.1" 500 47
ERROR 2025-05-26 22:16:58,603 openmrs_api 76352 129251286161088 환자 검색 실패 (검색어: 'joh'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=joh&v=full
ERROR 2025-05-26 22:16:58,604 log 76352 129251286161088 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:16:58,605 basehttp 76352 129251286161088 "GET /api/openmrs/patients/search/?q=joh HTTP/1.1" 500 47
ERROR 2025-05-26 22:16:58,797 openmrs_api 76352 129250732537536 환자 검색 실패 (검색어: 'john'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=john&v=full
ERROR 2025-05-26 22:16:58,798 log 76352 129250732537536 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:16:58,799 basehttp 76352 129250732537536 "GET /api/openmrs/patients/search/?q=john HTTP/1.1" 500 47
ERROR 2025-05-26 22:17:01,066 openmrs_api 76352 129250732537536 환자 검색 실패 (검색어: 'joh'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=joh&v=full
ERROR 2025-05-26 22:17:01,068 log 76352 129250732537536 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:17:01,069 basehttp 76352 129250732537536 "GET /api/openmrs/patients/search/?q=joh HTTP/1.1" 500 47
ERROR 2025-05-26 22:17:01,186 openmrs_api 76352 129251286161088 환자 검색 실패 (검색어: 'jo'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=jo&v=full
ERROR 2025-05-26 22:17:01,187 log 76352 129251286161088 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:17:01,188 basehttp 76352 129251286161088 "GET /api/openmrs/patients/search/?q=jo HTTP/1.1" 500 47
ERROR 2025-05-26 22:17:01,325 openmrs_api 76352 129250732537536 환자 검색 실패 (검색어: 'j'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=j&v=full
ERROR 2025-05-26 22:17:01,327 log 76352 129250732537536 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:17:01,328 basehttp 76352 129250732537536 "GET /api/openmrs/patients/search/?q=j HTTP/1.1" 500 47
INFO 2025-05-26 22:17:57,157 autoreload 76352 129255361589504 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:17:58,690 autoreload 77660 123916270887168 Watching for file changes with StatReloader
INFO 2025-05-26 22:18:36,915 autoreload 77660 123916270887168 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:18:38,548 autoreload 77741 132284283949312 Watching for file changes with StatReloader
INFO 2025-05-26 22:18:42,550 views 77741 132280352368320 OpenMRS 연결 성공
INFO 2025-05-26 22:18:42,562 orthanc_api 77741 132280352368320 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:18:42,565 views 77741 132280352368320 Orthanc 연결 성공
INFO 2025-05-26 22:18:42,570 basehttp 77741 132280352368320 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:18:42,792 views 77741 132280352368320 OpenMRS 연결 성공
INFO 2025-05-26 22:18:42,796 orthanc_api 77741 132280352368320 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:18:42,797 views 77741 132280352368320 Orthanc 연결 성공
INFO 2025-05-26 22:18:42,798 basehttp 77741 132280352368320 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:18:47,258 views 77741 132280334534336 OpenMRS 연결 성공
INFO 2025-05-26 22:18:47,265 orthanc_api 77741 132280334534336 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:18:47,265 views 77741 132280334534336 Orthanc 연결 성공
INFO 2025-05-26 22:18:47,266 basehttp 77741 132280334534336 "GET /api/test-connections/ HTTP/1.1" 200 66
ERROR 2025-05-26 22:18:50,259 openmrs_api 77741 132280334534336 환자 검색 실패 (검색어: 'j'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=j&v=full
ERROR 2025-05-26 22:18:50,261 log 77741 132280334534336 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:18:50,262 basehttp 77741 132280334534336 "GET /api/openmrs/patients/search/?q=j HTTP/1.1" 500 47
ERROR 2025-05-26 22:18:50,609 openmrs_api 77741 132280334534336 환자 검색 실패 (검색어: 'jo'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=jo&v=full
ERROR 2025-05-26 22:18:50,611 log 77741 132280334534336 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:18:50,612 basehttp 77741 132280334534336 "GET /api/openmrs/patients/search/?q=jo HTTP/1.1" 500 47
ERROR 2025-05-26 22:18:50,722 openmrs_api 77741 132280326141632 환자 검색 실패 (검색어: 'joh'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=joh&v=full
ERROR 2025-05-26 22:18:50,724 log 77741 132280326141632 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:18:50,725 basehttp 77741 132280326141632 "GET /api/openmrs/patients/search/?q=joh HTTP/1.1" 500 47
ERROR 2025-05-26 22:18:51,450 openmrs_api 77741 132280326141632 환자 검색 실패 (검색어: 'john'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=john&v=full
ERROR 2025-05-26 22:18:51,452 log 77741 132280326141632 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:18:51,453 basehttp 77741 132280326141632 "GET /api/openmrs/patients/search/?q=john HTTP/1.1" 500 47
ERROR 2025-05-26 22:19:59,221 openmrs_api 77741 132280309356224 환자 검색 실패 (검색어: 'john'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=john&v=full
ERROR 2025-05-26 22:19:59,222 log 77741 132280309356224 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:19:59,223 basehttp 77741 132280309356224 "GET /api/openmrs/patients/search/?q=john HTTP/1.1" 500 47
WARNING 2025-05-26 22:19:59,502 log 77741 132280309356224 Not Found: /favicon.ico
WARNING 2025-05-26 22:19:59,503 basehttp 77741 132280309356224 "GET /favicon.ico HTTP/1.1" 404 2885
WARNING 2025-05-26 22:20:03,023 log 77741 132279951156928 Bad Request: /api/openmrs/patients/search/
WARNING 2025-05-26 22:20:03,025 basehttp 77741 132279951156928 "GET /api/openmrs/patients/search/?q= HTTP/1.1" 400 43
WARNING 2025-05-26 22:20:05,890 log 77741 132279951156928 Bad Request: /api/openmrs/patients/search/
WARNING 2025-05-26 22:20:05,891 basehttp 77741 132279951156928 "GET /api/openmrs/patients/search/ HTTP/1.1" 400 43
WARNING 2025-05-26 22:20:09,749 log 77741 132279951156928 Not Found: /api/openmrs/patients/
WARNING 2025-05-26 22:20:09,750 basehttp 77741 132279951156928 "GET /api/openmrs/patients/ HTTP/1.1" 404 7122
INFO 2025-05-26 22:20:17,190 basehttp 77741 132279951156928 "GET /api/openmrs/patients/search HTTP/1.1" 301 0
WARNING 2025-05-26 22:20:17,380 log 77741 132279942764224 Bad Request: /api/openmrs/patients/search/
WARNING 2025-05-26 22:20:17,381 basehttp 77741 132279942764224 "GET /api/openmrs/patients/search/ HTTP/1.1" 400 43
WARNING 2025-05-26 22:20:21,222 log 77741 132279942764224 Not Found: /api/openmrs/patients/
WARNING 2025-05-26 22:20:21,223 basehttp 77741 132279942764224 "GET /api/openmrs/patients/ HTTP/1.1" 404 7122
ERROR 2025-05-26 22:31:44,551 openmrs_api 77741 132279925978816 환자 검색 실패 (검색어: 'j'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=j&v=full
ERROR 2025-05-26 22:31:44,553 log 77741 132279925978816 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:44,554 basehttp 77741 132279925978816 "GET /api/openmrs/patients/search/?q=j HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:44,636 openmrs_api 77741 132279917586112 환자 검색 실패 (검색어: 'jo'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=jo&v=full
ERROR 2025-05-26 22:31:44,638 log 77741 132279917586112 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:44,638 basehttp 77741 132279917586112 "GET /api/openmrs/patients/search/?q=jo HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:44,814 openmrs_api 77741 132279951156928 환자 검색 실패 (검색어: 'john'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=john&v=full
ERROR 2025-05-26 22:31:44,818 log 77741 132279951156928 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:44,820 basehttp 77741 132279951156928 "GET /api/openmrs/patients/search/?q=john HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:44,838 openmrs_api 77741 132279909193408 환자 검색 실패 (검색어: 'joh'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=joh&v=full
ERROR 2025-05-26 22:31:44,840 log 77741 132279909193408 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:44,842 basehttp 77741 132279909193408 "GET /api/openmrs/patients/search/?q=joh HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:46,874 openmrs_api 77741 132279347177152 환자 검색 실패 (검색어: 'joh'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=joh&v=full
ERROR 2025-05-26 22:31:46,876 log 77741 132279347177152 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:46,877 basehttp 77741 132279347177152 "GET /api/openmrs/patients/search/?q=joh HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:47,135 openmrs_api 77741 132279338784448 환자 검색 실패 (검색어: 'j'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=j&v=full
ERROR 2025-05-26 22:31:47,146 log 77741 132279338784448 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:47,147 basehttp 77741 132279338784448 "GET /api/openmrs/patients/search/?q=j HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:47,182 openmrs_api 77741 132279330391744 환자 검색 실패 (검색어: 'jo'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=jo&v=full
ERROR 2025-05-26 22:31:47,185 log 77741 132279330391744 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:47,187 basehttp 77741 132279330391744 "GET /api/openmrs/patients/search/?q=jo HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:47,307 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'a'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=a&v=full
ERROR 2025-05-26 22:31:47,310 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:47,312 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=a HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:48,423 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'b'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=b&v=full
ERROR 2025-05-26 22:31:48,425 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:48,427 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=b HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:49,721 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'c'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=c&v=full
ERROR 2025-05-26 22:31:49,723 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:49,725 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=c HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:50,988 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'd'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=d&v=full
ERROR 2025-05-26 22:31:50,990 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:50,991 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=d HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:52,210 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'e'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=e&v=full
ERROR 2025-05-26 22:31:52,213 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:52,216 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=e HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:53,351 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'f'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=f&v=full
ERROR 2025-05-26 22:31:53,352 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:53,353 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=f HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:54,458 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'g'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=g&v=full
ERROR 2025-05-26 22:31:54,460 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:54,461 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=g HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:55,994 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'h'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=h&v=full
ERROR 2025-05-26 22:31:55,996 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:55,998 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=h HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:57,266 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'i'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=i&v=full
ERROR 2025-05-26 22:31:57,268 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:57,269 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=i HTTP/1.1" 500 47
ERROR 2025-05-26 22:31:58,431 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'j'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=j&v=full
ERROR 2025-05-26 22:31:58,433 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:31:58,434 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=j HTTP/1.1" 500 47
ERROR 2025-05-26 22:32:00,142 openmrs_api 77741 132279321999040 환자 검색 실패 (검색어: 'k'): 401 Client Error: Unauthorized for url: http://127.0.0.1:8082/openmrs/ws/rest/v1/patient?q=k&v=full
ERROR 2025-05-26 22:32:00,144 log 77741 132279321999040 Internal Server Error: /api/openmrs/patients/search/
ERROR 2025-05-26 22:32:00,145 basehttp 77741 132279321999040 "GET /api/openmrs/patients/search/?q=k HTTP/1.1" 500 47
INFO 2025-05-26 22:32:01,452 views 77741 132279321999040 OpenMRS 연결 성공
INFO 2025-05-26 22:32:01,458 orthanc_api 77741 132279321999040 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:32:01,459 views 77741 132279321999040 Orthanc 연결 성공
INFO 2025-05-26 22:32:01,461 basehttp 77741 132279321999040 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:32:04,588 views 77741 132279321999040 OpenMRS 연결 성공
INFO 2025-05-26 22:32:04,592 orthanc_api 77741 132279321999040 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:32:04,593 views 77741 132279321999040 Orthanc 연결 성공
INFO 2025-05-26 22:32:04,594 basehttp 77741 132279321999040 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:32:07,373 views 77741 132279321999040 OpenMRS 연결 성공
INFO 2025-05-26 22:32:07,381 orthanc_api 77741 132279321999040 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:32:07,382 views 77741 132279321999040 Orthanc 연결 성공
INFO 2025-05-26 22:32:07,384 basehttp 77741 132279321999040 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:32:07,602 views 77741 132279321999040 OpenMRS 연결 성공
INFO 2025-05-26 22:32:07,609 orthanc_api 77741 132279321999040 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:32:07,609 views 77741 132279321999040 Orthanc 연결 성공
INFO 2025-05-26 22:32:07,611 basehttp 77741 132279321999040 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:32:08,606 views 77741 132279321999040 OpenMRS 연결 성공
INFO 2025-05-26 22:32:08,624 orthanc_api 77741 132279321999040 Orthanc 연결 성공:  버전 1.12.0
INFO 2025-05-26 22:32:08,635 views 77741 132279321999040 Orthanc 연결 성공
INFO 2025-05-26 22:32:08,637 basehttp 77741 132279321999040 "GET /api/test-connections/ HTTP/1.1" 200 66
INFO 2025-05-26 22:34:31,582 autoreload 77741 132284283949312 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:34:33,191 autoreload 78563 126572054098176 Watching for file changes with StatReloader
INFO 2025-05-26 22:35:39,825 autoreload 78563 126572054098176 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:35:41,328 autoreload 78628 140462194135296 Watching for file changes with StatReloader
INFO 2025-05-26 22:36:47,677 autoreload 78628 140462194135296 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:36:48,973 autoreload 78686 126504146645248 Watching for file changes with StatReloader
INFO 2025-05-26 22:37:09,645 autoreload 78686 126504146645248 /home/medical_system/backend/backend/settings.py changed, reloading.
INFO 2025-05-26 22:37:10,903 autoreload 78726 136406095466752 Watching for file changes with StatReloader
WARNING 2025-05-26 23:17:15,173 log 78726 136402162017984 Not Found: /
WARNING 2025-05-26 23:17:15,175 basehttp 78726 136402162017984 "GET / HTTP/1.1" 404 2834
ERROR 2025-05-26 23:19:07,566 exception 78726 136402134742720 Invalid HTTP_HOST header: 'www.google.com:443'. You may need to add 'www.google.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/medical_system/venv/lib/python3.13/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.google.com:443'. You may need to add 'www.google.com' to ALLOWED_HOSTS.
WARNING 2025-05-26 23:19:07,606 log 78726 136402134742720 Bad Request: /www.google.com:443
WARNING 2025-05-26 23:19:07,607 basehttp 78726 136402134742720 "CONNECT www.google.com:443 HTTP/1.1" 400 76055
